### PR TITLE
Don't capture stack traces by default.

### LINKED ISSUE #457: `pub run test` slow initialization.
`pub run test` initializes really slow.

When I write:

```bash
pub run test -p vm test/library_test.dart
```

runner waits around 25 seconds and then run everything in 7 seconds.

At the same time, writing

```bash
dart test/library_test.dart
```

will end in just 4 seconds.

I don't mind a bit slower execution, but having to wait half of minute is too much, and this time tends to increase as I add more tests.

You can check everything yourself on [dikmax/md_proc](https://github.com/dikmax/md_proc/tree/rewrite) branch `rewrite`.

### PR DESCRIPTION
**Pull request by nex3**
Stack traces are now only captured for the JSON reporter. Capturing
traces was slow enough to be a serious problem for test suites with many
tests.

Closes #457

### CODE REVIEW

File: lib/src/backend/declarer.dart [hunk 1]
```diff
@@ -77,10 +80,16 @@ class Declarer {
...
   /// If [metadata] is passed, it's used as the metadata for the implicit root
   /// group.
-  Declarer([Metadata metadata])
-      : this._(null, null, metadata == null ? new Metadata() : metadata, null);
+  ///
+  /// If [collectTraces] is `true`, this will set [GroupEntry.trace] for all
+  /// entries built by the declarer. Note that this can be noticeably slow when
+  /// thousands of tests are being declared (see #457).
+  Declarer({Metadata metadata, bool collectTraces: false})
+      : this._(null, null, metadata == null ? new Metadata() : metadata,
```
Comment (jmesserly) [inline lib/src/backend/declarer.dart]: perhaps: `metadata ?? new Metadata` ?

File: CHANGELOG.md [hunk 2]
```diff
@@ -1,3 +1,8 @@
+## 0.12.15+8
```
Comment (jmesserly) [inline CHANGELOG.md]: the pubspec version below is `0.12.16-dev`, was that meant to be consistent?

File: lib/src/backend/declarer.dart (hunk 1 above)
Comment (nex3) [inline lib/src/backend/declarer.dart]: Done.

File: CHANGELOG.md (hunk 2 above)
Comment (nex3) [inline CHANGELOG.md]: Unfortunate, but intended. Ideally the pubspec would be `0.12.15+8-dev`, but that's not allowed by semver, so we use the next-lowest dev version instead. If we release before adding any new features, it'll match the changelog.

Comment (jmesserly) [inline CHANGELOG.md]: ah, gotcha, interesting convention. So not necessarily intending to release right away. Makes sense.

Comment (nex3) [inline CHANGELOG.md]: Yeah, `-dev` always means "not intended for immediate release".

File: lib/src/backend/declarer.dart [hunk 3]
```diff
@@ -77,10 +80,15 @@ class Declarer {
...
   /// If [metadata] is passed, it's used as the metadata for the implicit root
   /// group.
-  Declarer([Metadata metadata])
-      : this._(null, null, metadata == null ? new Metadata() : metadata, null);
+  ///
+  /// If [collectTraces] is `true`, this will set [GroupEntry.trace] for all
+  /// entries built by the declarer. Note that this can be noticeably slow when
+  /// thousands of tests are being declared (see #457).
+  Declarer({Metadata metadata, bool collectTraces: false})
+      : this._(null, null, metadata? ?? new Metadata(), collectTraces, null);
```
Comment (kevmoo) [inline lib/src/backend/declarer.dart]: @nex3 OOPS! `metadata? ??` – breakage
