### PR TITLE
fix(test_core): fix `writeCoverage` to handle a `null` hit map

### LINKED ISSUE #2562: coverage breaks with `@Tag` in v1.27.0
```dart
@Tags(['pull-request-only'])
library ensure_build_test;

import 'package:build_verify/build_verify.dart';
import 'package:test/test.dart';

void main() {
  test('ensure_build', () {
    expectBuildClean(packageRelativeDirectory: 'packages/bloc_tools');
  });
}
```

Test fails in v1.27.0 of pkg:test but passes in v1.26.3.
Removing `@Tags(...)` also makes the tests pass.

```sh
$ dart test --coverage=coverage && dart pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.dart_tool/package_config.json --report-on=lib
00:00 +0: test/ensure_build_test.dart: (suite)                                                                                                                                                                                                                                                                                                                                                                                                                                                               
  Skip: Should only be run during pull request
00:00 +0 ~1: test/ensure_build_test.dart: (suite)                                                                                                                                                                                                                                                                                                                                                                                                                                                            type 'Null' is not a subtype of type 'List<Map<String, dynamic>>' in type cast
package:test_core/src/runner/coverage.dart 33:48  writeCoverage
package:test_core/src/runner/engine.dart 307:17   Engine.run.<fn>.<fn>
package:async/src/future_group.dart 79:15         FutureGroup.add.<fn>

This is an unexpected error. Please file an issue at http://github.com/dart-lang/test
with the stack trace and instructions for reproducing the error.
Unhandled exception:
type 'Null' is not a subtype of type 'List<Map<String, dynamic>>' in type cast
#0      writeCoverage (package:test_core/src/runner/coverage.dart:33:48)
<asynchronous suspension>
#1      Engine.run.<anonymous closure>.<anonymous closure> (package:test_core/src/runner/engine.dart:307:17)
<asynchronous suspension>
#2      FutureGroup.add.<anonymous closure> (package:async/src/future_group.dart:79:15)
<asynchronous suspension>
```

Link to CI failure: https://github.com/felangel/bloc/actions/runs/19545116043/job/55961821864?pr=4676

### PR DESCRIPTION
**Pull request by felangel**
- fix(test_core): fix `writeCoverage` to handle a `null` hit map
  - closes #2562
---

- [X] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.

**Note**: The Dart team is trialing Gemini Code Assist. Don't take its comments as final Dart team feedback. Use the suggestions if they're helpful; otherwise, wait for a human reviewer.

</details>

### CODE REVIEW

File: pkgs/test_core/lib/src/runner/coverage.dart [hunk 1]
```diff
@@ -30,7 +30,9 @@ Future<Coverage> writeCoverage(
     await out.flush();
     await out.close();
   }
-  return HitMap.parseJson(coverage['coverage'] as List<Map<String, dynamic>>);
+  final hitMapJson = coverage['coverage'] as List<Map<String, dynamic>>?;
+  if (hitMapJson == null) return const {};
+  return HitMap.parseJson(hitMapJson);
```
Comment (kevmoo) [inline pkgs/test_core/lib/src/runner/coverage.dart]:
```suggestion
  return hitMapJson == null ? const {} : HitMap.parseJson(hitMapJson);
```

**Review by kevmoo — APPROVED** [review]
Awesome!
