### PR TITLE
fix: improve error reporting on GitHub

### LINKED ISSUE #2628: Make finding the failing tests on github easier
Searching for the test that actually failed in the github UI is often REALLY hard.

could we just omit the green bits? Or collapse them all?

Image

### PR DESCRIPTION
**Pull request by kevmoo**
Group success and skip so it's easy to see the failures!
Update skip icon to ⚠️ so they are easier to scan

Fixes https://github.com/dart-lang/test/issues/2628

### CODE REVIEW

**Comment by kevmoo** [comment]
image

**Comment by kevmoo** [comment]
image

File: pkgs/test/test/runner/github_reporter_test.dart [hunk 1]
```diff
@@ -242,9 +260,11 @@ void main() {
           test('skip 2', () {}, skip: true);
           test('skip 3', () {}, skip: true);''',
         '''
-          ❎ skip 1 (skipped)
-          ❎ skip 2 (skipped)
-          ❎ skip 3 (skipped)
+          ::group::⚠️ Skipped tests
```
Comment (natebosch) [inline pkgs/test/test/runner/github_reporter_test.dart]: I think I'm on board with moving away from ❎ for skips. I don't know that I want to make them look as scary as ⚠️

What do you think about ⏭️

Comment (kevmoo) [reply pkgs/test/test/runner/github_reporter_test.dart]: sure! Just a different color...

**Comment by kevmoo** [comment]
@natebosch – rebased on latest - hoping for green!

**Review by natebosch — APPROVED** [review]
