### PR TITLE
Fix[test_api]: printOnFailure check current invoker

### LINKED ISSUE #1340: printOnFailure should explicitly check and throw if there is no current invoker
Today you get a pretty confusing error if you call it outside a test zone, something like:

```
 The method 'printOnFailure' was called on null.
  Receiver: null
  Tried calling: printOnFailure(<your-message>)
```

### PR DESCRIPTION
**Pull request by ayshiff**
Closes #1340

This PR adds a check within `printOnFailure ` and throw an exception if there is no current invoker.

Please let me know if you want me to add some tests to check the behavior of the function.

### CODE REVIEW

File: pkgs/test_api/lib/src/scaffolding/utils.dart [hunk 1]
```diff
@@ -33,7 +33,14 @@ void registerException(Object error,
 /// without cluttering the output for successful tests. Note that unlike
 /// [print], each individual message passed to [printOnFailure] will be
 /// separated by a blank line.
-void printOnFailure(String message) => Invoker.current!.printOnFailure(message);
+void printOnFailure(String message) {
+  var invoker = Invoker.current;
+  if (invoker == null) {
+    throw Exception(
+        'There is no current invoker. Please make sure that you are making the call inside a test zone.');
```
Comment (jakemac53) [inline pkgs/test_api/lib/src/scaffolding/utils.dart:40]:
```suggestion
        'There is no current invoker. Please make sure that you are making the '
        'call inside a test zone.');
```

File: pkgs/test_api/lib/src/scaffolding/utils.dart [hunk 2]
```diff
@@ -33,7 +33,15 @@ void registerException(Object error,
 /// without cluttering the output for successful tests. Note that unlike
 /// [print], each individual message passed to [printOnFailure] will be
 /// separated by a blank line.
-void printOnFailure(String message) => Invoker.current!.printOnFailure(message);
+void printOnFailure(String message) {
+  var invoker = Invoker.current;
+  if (invoker == null) {
+    throw Exception(
```
Comment (jakemac53) [inline pkgs/test_api/lib/src/scaffolding/utils.dart:39]:
```suggestion
    throw StateError(
```

**Comment by ayshiff** [comment]
I don't know why unit tests of `integration_tests/nnbd_opted_out` are failing on Windows.
@jakemac53 Do you have an idea?

**Comment by jakemac53** [comment]
Pretty sure its just a flake will restart the jobs

**Comment by jakemac53** [comment]
Hmm there does appear to be some actual breakage going on, I am going to check if its an issue on master (presumably it is).

**Review by jakemac53 — APPROVED** [review]

**Comment by jakemac53** [comment]
Ok this is now published, thanks!
