### PR TITLE
Fix formatStackTrace() in dart path/to/test.dart

### LINKED ISSUE #786: NoSuchMethodError: The method 'formatStackTrace' was called on null
Sorry in advance: I don't know if this issue is a Dart one or a Travis CI one (or even with the `test` package itself).

I've tests that are OK when I run them locally (using Dart 2.0.0-dev.38 on Ubuntu 17.10, with `test` v0.12.32+1):

```
$ pub run grinder test
grinder running test

test
  /usr/lib/dart/bin/dart --enable-vm-service --pause-isolates-on-exit test/all.dart
  /usr/lib/dart/bin/pub run coverage:collect_coverage --out=var/coverage.json --resume-isolates --wait-paused
  Observatory listening on http://127.0.0.1:8181/
  00:00 +0: Client constructor should throw an error if the credentials are invalid
  00:00 +1: Client .sendMessage() should not send invalid messages
  00:00 +2: Client .sendMessage() should throw a `ClientException` if a network error occurred
  00:00 +3: Client .sendMessage() should send valid messages with valid credentials
  00:00 +4: All tests passed!
  /usr/lib/dart/bin/pub run coverage:format_coverage --in=var/coverage.json --lcov --out=var/lcov.info --packages=.packages --report-on=lib

finished in 3.2 seconds
```

When the tests are run by Travis CI (Dart 2.0.0-dev.38 on Ubuntu 14.10, `test` v0.12.32+1), I get the following error:

```
$ pub run grinder test
grinder running test
test
  /home/travis/dart-sdk/bin/dart --enable-vm-service --pause-isolates-on-exit test/all.dart
  /home/travis/dart-sdk/bin/pub run coverage:collect_coverage --out=var/coverage.json --resume-isolates --wait-paused
  Observatory listening on http://127.0.0.1:8181/
  00:00 +0: Client constructor should throw an error if the credentials are invalid
  00:00 +1: Client .sendMessage() should not send invalid messages
  00:00 +2: Client .sendMessage() should throw a `ClientException` if a network error occurred
  00:00 +2 -1: Client .sendMessage() should throw a `ClientException` if a network error occurred [E]
    NoSuchMethodError: The method 'formatStackTrace' was called on null.
    Receiver: null
    Tried calling: formatStackTrace(Instance of 'Chain', verbose: null)
    dart:core-patch/dart:core/object_patch.dart 46                Object.noSuchMethod
    package:test/src/frontend/format_stack_trace.dart 15:33       formatStackTrace
    package:test/src/frontend/throws_matcher.dart 98:27           Throws._check
[...]
```

The full stack trace is available here:
https://travis-ci.org/cedx/free-mobile.dart/builds/354006632

The code that raises this issue is available here:
https://github.com/cedx/free-mobile.dart/blob/master/test/http/client_test.dart#L20

### PR DESCRIPTION
**Pull request by nex3**
Closes #786

### CODE REVIEW

File: lib/src/frontend/format_stack_trace.dart [hunk 1]
```diff
@@ -6,10 +6,17 @@ import 'package:stack_trace/stack_trace.dart';
...
+final _defaultFormatter = new StackTraceFormatter();
+
 /// Converts [stackTrace] to a [Chain] according to the current test's
 /// configuration.
 ///
 /// If [verbose] is `true`, this doesn't fold out irrelevant stack frames. It
 /// defaults to the current test's `verbose_trace` configuration.
 Chain formatStackTrace(StackTrace stackTrace, {bool verbose}) =>
-    StackTraceFormatter.current.formatStackTrace(stackTrace, verbose: verbose);
+    (StackTraceFormatter.current ?? _defaultFormatter)
```
Comment (grouma) [inline lib/src/frontend/format_stack_trace.dart]: Ahh beat me to it. I meant to do this change as I had to do a similar work around for Bolt.
