### PR TITLE
Print "[E]" after failing tests.

### LINKED ISSUE #554: Add an option to print a failure summary after tests run
At the moment, there is no clean way to copy-paste failures after a run.

Even printing "FAILURE" on the line when a new failure is found would be useful – then one could search/grep

### PR DESCRIPTION
**Pull request by nex3**
Closes #554

### CODE REVIEW

File: lib/src/runner/reporter/compact.dart [hunk 1]
```diff
@@ -198,7 +198,7 @@ class CompactReporter implements Reporter {
   void _onError(LiveTest liveTest, error, StackTrace stackTrace) {
     if (liveTest.state.status != Status.complete) return;
 
-    _progressLine(_description(liveTest), truncate: false);
+    _progressLine(_description(liveTest) + " $_bold$_red[E]$_noColor");
```
Comment (kevmoo) [inline lib/src/runner/reporter/compact.dart]: no longer truncated – intentional?

Comment (nex3) [inline lib/src/runner/reporter/compact.dart]: Done.
